In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import classification_report
print("OK")

OK

In [2]:
import sys
sys.path.append("..")

from src.features import extract_symptoms
import pandas as pd

# load data
df_raw = pd.read_excel("../data/raw/covid.xlsx")

# run function
df_symptoms = extract_symptoms(df_raw)

# check output
df_symptoms.head()

,Fever,Myalgia,Chills,Fatigue,Sweating,Anorexia,Sore_Throat,Sneezing,Cough,Dyspnea,...,Ageusia,Chest_Pain,Palpitations,Nausea,Vomiting,Abdominal_Pain,Diarrhea,Depression,Sleep_Disorder,Headache
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [3]:
import sys
sys.path.append("..")

#import importlib
import src.features as features

#importlib.reload(features)

df_pmh = features.extract_pmh(df_raw)

print(df_pmh.shape)
df_pmh.head()

(16780, 28)

,Cancer,Organ_Transplant,Chronic_Kidney_Disease,Dialysis,Cancer_Type,Solid_Organ_Transplant,Asthma,Chronic_Respiratory_Disease,Hypertension,Myocardial_Infarction,...,Seizure,Diabetes_Type1,Diabetes_Type2,Hypothyroidism,Hyperthyroidism,Insulin_Use,Rheumatoid_Arthritis,Lupus,Behcet,Sjogren
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#import importlib
import src.features as features

#importlib.reload(features)

df_vax = features.extract_vaccination(df_raw)

print(df_vax.shape)
df_vax.head()

(16780, 2)

   Vaccinated  Vaccine_Doses
0           0            0.0
1           0            0.0
2           0            0.0
3           0            0.0
4           1            2.0

In [5]:
print("Vaccinated %:", round(df_vax['Vaccinated'].mean() * 100, 2))
df_vax['Vaccine_Doses'].value_counts().sort_index()

Vaccinated %: 3.43

Vaccine_Doses
0.0    16205
1.0      107
2.0      354
3.0      106
4.0        8
Name: count, dtype: int64

In [6]:
import importlib
import src.features as features

importlib.reload(features)

df_final = features.build_features(df_raw)

print(df_final.shape)
df_final.head()

(16780, 55)

,Fever,Myalgia,Chills,Fatigue,Sweating,Anorexia,Sore_Throat,Sneezing,Cough,Dyspnea,...,Diabetes_Type2,Hypothyroidism,Hyperthyroidism,Insulin_Use,Rheumatoid_Arthritis,Lupus,Behcet,Sjogren,Vaccinated,Vaccine_Doses
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0.0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0.0
4,0,0,1,0,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,1,2.0

In [7]:
# 🎯 Step 1: Create target (CT lung involvement → severity)

df_target = df_raw['Unnamed: 69'].iloc[3:].reset_index(drop=True)

# Convert to binary:
# if there is any text → 1 (lung involvement)
# if empty → 0 (no involvement)

df_target = df_target.notna().astype(int)

# Check distribution
print("Target distribution:")
print(df_target.value_counts())

Target distribution:
Unnamed: 69
0    16588
1      192
Name: count, dtype: int64

In [13]:
#  feature و target

X = df_final.copy()
y = df_target

X = X.loc[y.index]

print(X.shape, y.shape)

(16780, 55) (16780,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [15]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Before SMOTE:\n", y_train.value_counts())
print("After SMOTE:\n", y_train_res.value_counts())

Before SMOTE:
 Unnamed: 69
0    13270
1      154
Name: count, dtype: int64
After SMOTE:
 Unnamed: 69
0    13270
1    13270
Name: count, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=1000)

model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.69      0.82      3318
           1       0.02      0.42      0.03        38

    accuracy                           0.69      3356
   macro avg       0.50      0.56      0.42      3356
weighted avg       0.98      0.69      0.81      3356

In [17]:
from sklearn.metrics import classification_report

# Get predicted probabilities for the severe class (class 1)
y_proba = model.predict_proba(X_test)[:, 1]

# Try a custom threshold instead of the default 0.5
threshold = 0.2

# Convert probabilities to class labels based on the selected threshold
y_pred_threshold = (y_proba >= threshold).astype(int)

# Evaluate model performance with the new threshold
print(classification_report(y_test, y_pred_threshold))

              precision    recall  f1-score   support

           0       0.99      0.51      0.68      3318
           1       0.01      0.61      0.03        38

    accuracy                           0.51      3356
   macro avg       0.50      0.56      0.35      3356
weighted avg       0.98      0.51      0.67      3356

In [18]:
for threshold in [0.1, 0.2, 0.3, 0.4, 0.5]:
    y_pred_threshold = (y_proba >= threshold).astype(int)
    
    print("Threshold:", threshold)
    print(classification_report(y_test, y_pred_threshold))
    print("-" * 50)

Threshold: 0.1
              precision    recall  f1-score   support

           0       0.99      0.42      0.59      3318
           1       0.01      0.74      0.03        38

    accuracy                           0.42      3356
   macro avg       0.50      0.58      0.31      3356
weighted avg       0.98      0.42      0.58      3356

--------------------------------------------------
Threshold: 0.2
              precision    recall  f1-score   support

           0       0.99      0.51      0.68      3318
           1       0.01      0.61      0.03        38

    accuracy                           0.51      3356
   macro avg       0.50      0.56      0.35      3356
weighted avg       0.98      0.51      0.67      3356

--------------------------------------------------
Threshold: 0.3
              precision    recall  f1-score   support

           0       0.99      0.58      0.73      3318
           1       0.01      0.55      0.03        38

    accuracy                           0.58      3356
   macro avg       0.50      0.57      0.38      3356
weighted avg       0.98      0.58      0.72      3356

--------------------------------------------------
Threshold: 0.4
              precision    recall  f1-score   support

           0       0.99      0.63      0.77      3318
           1       0.01      0.45      0.03        38

    accuracy                           0.63      3356
   macro avg       0.50      0.54      0.40      3356
weighted avg       0.98      0.63      0.76      3356

--------------------------------------------------
Threshold: 0.5
              precision    recall  f1-score   support

           0       0.99      0.69      0.82      3318
           1       0.02      0.42      0.03        38

    accuracy                           0.69      3356
   macro avg       0.50      0.56      0.42      3356
weighted avg       0.98      0.69      0.81      3356

--------------------------------------------------

In [20]:
!pip install xgboost

Collecting xgboost
  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/1f/3d/1661dd114a914a67e3f7ab66fa1382e7599c2a8c340f314ad30a3e2b4d08/xgboost-3.2.0-py3-none-win_amd64.whl.metadata
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\ati\anaconda3\lib\site-packages (from xgboost) (1.24.3)
Requirement already satisfied: scipy in c:\users\ati\anaconda3\lib\site-packages (from xgboost) (1.10.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB 1.3 MB/s eta 0:01:20
   ---------------------------------------- 0.1/101.7 MB 1.1 MB/s eta 0:01:37
   ---------------------------------------- 0.2/101.7 MB 1.1 MB/s eta 0:01:29
   ---------------------------------------- 0.3/101.7 MB 1.3 MB/s eta 0:01:18
   ---------------------------------------- 0.4/101.7 MB 1.8 MB/s eta 0:00:58
   ---------------------------------------- 0.7/101.7 MB 2.3 MB/s eta 0:00:44
   ---------------------------------------- 0.7/101.7 MB 2.3 MB/s eta 0:00:44
   ---------------------------------------- 0.9/101.7 MB 2.5 MB/s eta 0:00:41
    --------------------------------------- 1.4/101.7 MB 3.2 MB/s eta 0:00:32
    --------------------------------------- 1.4/101.7 MB 3.2 MB/s eta 0:00:32
    --------------------------------------- 1.5/101.7 MB 3.0 MB/s eta 0:00:34
    --------------------------------------- 1.9/101.7 MB 3.6 MB/s eta 0:00:28
    --------------------------------------- 2.0/101.7 MB 3.3 MB/s eta 0:00:30
    --------------------------------------- 2.2/101.7 MB 3.4 MB/s eta 0:00:30
    --------------------------------------- 2.4/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 2.7/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 2.9/101.7 MB 3.6 MB/s eta 0:00:28
   - -------------------------------------- 3.0/101.7 MB 3.5 MB/s eta 0:00:28
   - -------------------------------------- 3.3/101.7 MB 3.6 MB/s eta 0:00:28
   - -------------------------------------- 3.5/101.7 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 3.8/101.7 MB 3.8 MB/s eta 0:00:26
   - -------------------------------------- 3.9/101.7 MB 3.8 MB/s eta 0:00:27
   - -------------------------------------- 4.2/101.7 MB 3.8 MB/s eta 0:00:26
   - -------------------------------------- 4.4/101.7 MB 3.9 MB/s eta 0:00:26
   - -------------------------------------- 4.6/101.7 MB 3.9 MB/s eta 0:00:26
   - -------------------------------------- 4.8/101.7 MB 3.9 MB/s eta 0:00:26
   - -------------------------------------- 5.0/101.7 MB 3.9 MB/s eta 0:00:25
   -- ------------------------------------- 5.3/101.7 MB 4.0 MB/s eta 0:00:25
   -- ------------------------------------- 5.4/101.7 MB 4.0 MB/s eta 0:00:25
   -- ------------------------------------- 6.0/101.7 MB 4.1 MB/s eta 0:00:24
   -- ------------------------------------- 6.3/101.7 MB 4.1 MB/s eta 0:00:24
   -- ------------------------------------- 6.7/101.7 MB 4.1 MB/s eta 0:00:23
   -- ------------------------------------- 6.8/101.7 MB 4.2 MB/s eta 0:00:23
   -- ------------------------------------- 7.1/101.7 MB 4.1 MB/s eta 0:00:23
   -- ------------------------------------- 7.4/101.7 MB 4.2 MB/s eta 0:00:23
   -- ------------------------------------- 7.5/101.7 MB 4.2 MB/s eta 0:00:23
   --- ------------------------------------ 7.8/101.7 MB 4.2 MB/s eta 0:00:23
   --- ------------------------------------ 8.0/101.7 MB 4.2 MB/s eta 0:00:23
   --- ------------------------------------ 8.2/101.7 MB 4.2 MB/s eta 0:00:23
   --- ------------------------------------ 8.4/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 8.7/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 9.0/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 9.2/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 9.4/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 9.7/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 9.9/101.7 MB 4.4 MB/s eta 0:00:22
   ---- ----------------------------------- 10.2/101.7 MB 4.4 MB/s eta 0:00:21
   ---- ----------------------------------- 10.4/101.7 MB 4.6 MB/s eta 0:00:20
   ---- ----------------------------------- 10.7/101.7 MB 4.7 MB/s eta 0:00:20
   ---- ----------------------------------- 10.8/101.7 MB 4.6 MB/s eta 0:00:20
   ---- ----------------------------------- 10.8/101.7 MB 4.5 MB/s eta 0:00:20
   ---- ----------------------------------- 11.0/101.7 MB 4.7 MB/s eta 0:00:20
   ---- ----------------------------------- 11.3/101.7 MB 4.6 MB/s eta 0:00:20
   ---- ----------------------------------- 11.6/101.7 MB 4.6 MB/s eta 0:00:20
   ---- ----------------------------------- 11.8/101.7 MB 4.7 MB/s eta 0:00:20
   ---- ----------------------------------- 12.1/101.7 MB 4.6 MB/s eta 0:00:20
   ---- ----------------------------------- 12.3/101.7 MB 4.7 MB/s eta 0:00:20
   ---- ----------------------------------- 12.6/101.7 MB 4.7 MB/s eta 0:00:19
   ----- ---------------------------------- 12.8/101.7 MB 4.7 MB/s eta 0:00:19
   ----- ---------------------------------- 13.0/101.7 MB 4.7 MB/s eta 0:00:19
   ----- ---------------------------------- 13.3/101.7 MB 4.8 MB/s eta 0:00:19
   ----- ---------------------------------- 13.8/101.7 MB 4.8 MB/s eta 0:00:19
   ----- ---------------------------------- 14.2/101.7 MB 4.8 MB/s eta 0:00:19
   ----- ---------------------------------- 14.5/101.7 MB 4.8 MB/s eta 0:00:19
   ----- ---------------------------------- 14.7/101.7 MB 4.9 MB/s eta 0:00:18
   ----- ---------------------------------- 14.9/101.7 MB 4.9 MB/s eta 0:00:18
   ----- ---------------------------------- 15.2/101.7 MB 4.9 MB/s eta 0:00:18
   ------ --------------------------------- 15.4/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 15.6/101.7 MB 4.9 MB/s eta 0:00:18
   ------ --------------------------------- 15.7/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 16.0/101.7 MB 4.9 MB/s eta 0:00:18
   ------ --------------------------------- 16.2/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 16.4/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 16.7/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 16.9/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 17.1/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 17.4/101.7 MB 4.8 MB/s eta 0:00:18
   ------ --------------------------------- 17.6/101.7 MB 4.8 MB/s eta 0:00:18
   ------- -------------------------------- 17.9/101.7 MB 4.8 MB/s eta 0:00:18
   ------- -------------------------------- 18.1/101.7 MB 4.8 MB/s eta 0:00:18
   ------- -------------------------------- 18.3/101.7 MB 4.9 MB/s eta 0:00:18
   ------- -------------------------------- 18.6/101.7 MB 4.9 MB/s eta 0:00:18
   ------- -------------------------------- 18.8/101.7 MB 4.9 MB/s eta 0:00:18
   ------- -------------------------------- 19.1/101.7 MB 4.8 MB/s eta 0:00:18
   ------- -------------------------------- 19.3/101.7 MB 4.8 MB/s eta 0:00:17
   ------- -------------------------------- 19.6/101.7 MB 4.8 MB/s eta 0:00:17
   ------- -------------------------------- 19.8/101.7 MB 4.9 MB/s eta 0:00:17
   ------- -------------------------------- 20.0/101.7 MB 4.9 MB/s eta 0:00:17
   ------- -------------------------------- 20.2/101.7 MB 4.8 MB/s eta 0:00:17
   -------- ------------------------------- 20.4/101.7 MB 4.8 MB/s eta 0:00:18
   -------- ------------------------------- 20.7/101.7 MB 4.8 MB/s eta 0:00:17
   -------- ------------------------------- 20.9/101.7 MB 4.8 MB/s eta 0:00:17
   -------- ------------------------------- 21.0/101.7 MB 4.9 MB/s eta 0:00:17
   -------- ------------------------------- 21.3/101.7 MB 4.9 MB/s eta 0:00:17
   -------- ------------------------------- 21.6/101.7 MB 4.9 MB/s eta 0:00:17
   -------- ------------------------------- 21.7/101.7 MB 4.9 MB/s eta 0:00:17
   -------- ------------------------------- 22.0/101.7 MB 4.9 MB/s eta 0:00:17
   -------- ------------------------------- 22.1/101.7 MB 4.8 MB/s eta 0:00:17
   -------- ------------------------------- 22.3/101.7 MB 4.9 MB/s eta 0:00:17
   -------- ------------------------------- 22.6/101.7 MB 4.8 MB/s eta 0:00:17
   -------- ------------------------------- 22.9/101.7 MB 4.9 MB/s eta 0:00:17
   --------- ------------------------------ 23.1/101.7 MB 4.9 MB/s eta 0:00:17
   --------- ------------------------------ 23.4/101.7 MB 4.9 MB/s eta 0:00:17
   --------- ------------------------------ 23.6/101.7 MB 4.9 MB/s eta 0:00:17
   --------- ------------------------------ 23.8/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 24.0/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 24.2/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 24.4/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 24.6/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 24.9/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 25.1/101.7 MB 4.8 MB/s eta 0:00:17
   --------- ------------------------------ 25.4/101.7 MB 4.8 MB/s eta 0:00:16
   ---------- ----------------------------- 25.6/101.7 MB 4.8 MB/s eta 0:00:16
   ---------- ----------------------------- 25.8/101.7 MB 4.8 MB/s eta 0:00:16
   ---------- ----------------------------- 26.0/101.7 MB 4.8 MB/s eta 0:00:16
   ---------- ----------------------------- 26.2/101.7 MB 4.8 MB/s eta 0:00:16
   ---------- ----------------------------- 26.3/101.7 MB 4.7 MB/s eta 0:00:16
   ---------- ----------------------------- 26.6/101.7 MB 4.8 MB/s eta 0:00:16
   ---------- ----------------------------- 26.7/101.7 MB 4.7 MB/s eta 0:00:16
   ---------- ----------------------------- 26.9/101.7 MB 4.7 MB/s eta 0:00:16
   ---------- ----------------------------- 27.1/101.7 MB 4.7 MB/s eta 0:00:16
   ---------- ----------------------------- 27.1/101.7 MB 4.6 MB/s eta 0:00:17
   ---------- ----------------------------- 27.4/101.7 MB 4.6 MB/s eta 0:00:17
   ---------- ----------------------------- 27.4/101.7 MB 4.6 MB/s eta 0:00:17
   ---------- ----------------------------- 27.5/101.7 MB 4.5 MB/s eta 0:00:17
   ---------- ----------------------------- 27.7/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 28.0/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 28.2/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 28.5/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 28.7/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 28.9/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 29.2/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 29.4/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 29.7/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 29.9/101.7 MB 4.5 MB/s eta 0:00:17
   ----------- ---------------------------- 30.2/101.7 MB 4.5 MB/s eta 0:00:16
   ----------- ---------------------------- 30.4/101.7 MB 4.5 MB/s eta 0:00:16
   ------------ --------------------------- 30.7/101.7 MB 4.5 MB/s eta 0:00:16
   ------------ --------------------------- 30.9/101.7 MB 4.5 MB/s eta 0:00:16
   ------------ --------------------------- 31.2/101.7 MB 4.6 MB/s eta 0:00:16
   ------------ --------------------------- 31.4/101.7 MB 4.6 MB/s eta 0:00:16
   ------------ --------------------------- 31.6/101.7 MB 4.5 MB/s eta 0:00:16
   ------------ --------------------------- 31.8/101.7 MB 4.6 MB/s eta 0:00:16
   ------------ --------------------------- 32.1/101.7 MB 4.5 MB/s eta 0:00:16
   ------------ --------------------------- 32.3/101.7 MB 4.6 MB/s eta 0:00:16
   ------------ --------------------------- 32.5/101.7 MB 4.6 MB/s eta 0:00:15
   ------------ --------------------------- 32.8/101.7 MB 4.6 MB/s eta 0:00:15
   ------------ --------------------------- 33.0/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 33.2/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 33.4/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 33.7/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 33.9/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 34.2/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 34.3/101.7 MB 4.7 MB/s eta 0:00:15
   ------------- -------------------------- 34.6/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 34.9/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 35.1/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 35.3/101.7 MB 4.6 MB/s eta 0:00:15
   ------------- -------------------------- 35.5/101.7 MB 4.6 MB/s eta 0:00:15
   -------------- ------------------------- 35.8/101.7 MB 4.6 MB/s eta 0:00:15
   -------------- ------------------------- 36.0/101.7 MB 4.6 MB/s eta 0:00:15
   -------------- ------------------------- 36.1/101.7 MB 4.6 MB/s eta 0:00:15
   -------------- ------------------------- 36.4/101.7 MB 4.6 MB/s eta 0:00:15
   -------------- ------------------------- 36.6/101.7 MB 4.7 MB/s eta 0:00:14
   -------------- ------------------------- 36.9/101.7 MB 4.7 MB/s eta 0:00:14
   -------------- ------------------------- 37.1/101.7 MB 4.7 MB/s eta 0:00:14
   -------------- ------------------------- 37.4/101.7 MB 4.9 MB/s eta 0:00:14
   -------------- ------------------------- 37.6/101.7 MB 5.0 MB/s eta 0:00:13
   -------------- ------------------------- 37.9/101.7 MB 5.0 MB/s eta 0:00:13
   --------------- ------------------------ 38.1/101.7 MB 5.0 MB/s eta 0:00:13
   --------------- ------------------------ 38.4/101.7 MB 5.0 MB/s eta 0:00:13
   --------------- ------------------------ 38.7/101.7 MB 5.1 MB/s eta 0:00:13
   --------------- ------------------------ 38.9/101.7 MB 5.1 MB/s eta 0:00:13
   --------------- ------------------------ 39.1/101.7 MB 5.1 MB/s eta 0:00:13
   --------------- ------------------------ 39.4/101.7 MB 5.0 MB/s eta 0:00:13
   --------------- ------------------------ 39.6/101.7 MB 5.1 MB/s eta 0:00:13
   --------------- ------------------------ 39.9/101.7 MB 5.1 MB/s eta 0:00:13
   --------------- ------------------------ 40.1/101.7 MB 5.0 MB/s eta 0:00:13
   --------------- ------------------------ 40.3/101.7 MB 5.0 MB/s eta 0:00:13
   --------------- ------------------------ 40.6/101.7 MB 5.1 MB/s eta 0:00:13
   ---------------- ----------------------- 40.7/101.7 MB 5.0 MB/s eta 0:00:13
   ---------------- ----------------------- 41.0/101.7 MB 5.0 MB/s eta 0:00:13
   ---------------- ----------------------- 41.2/101.7 MB 5.0 MB/s eta 0:00:13
   ---------------- ----------------------- 41.5/101.7 MB 5.0 MB/s eta 0:00:13
   ---------------- ----------------------- 41.7/101.7 MB 5.0 MB/s eta 0:00:12
   ---------------- ----------------------- 41.9/101.7 MB 5.0 MB/s eta 0:00:12
   ---------------- ----------------------- 42.2/101.7 MB 5.0 MB/s eta 0:00:12
   ---------------- ----------------------- 42.4/101.7 MB 5.0 MB/s eta 0:00:12
   ---------------- ----------------------- 42.7/101.7 MB 5.0 MB/s eta 0:00:12
   ---------------- ----------------------- 43.0/101.7 MB 5.0 MB/s eta 0:00:12
   ---------------- ----------------------- 43.2/101.7 MB 5.0 MB/s eta 0:00:12
   ----------------- ---------------------- 43.5/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 43.7/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 43.9/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 44.2/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 44.5/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 44.7/101.7 MB 5.2 MB/s eta 0:00:12
   ----------------- ---------------------- 44.9/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 45.1/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 45.4/101.7 MB 5.1 MB/s eta 0:00:12
   ----------------- ---------------------- 45.4/101.7 MB 5.1 MB/s eta 0:00:12
   ------------------ --------------------- 45.8/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 46.0/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 46.2/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 46.4/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 46.7/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 46.8/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 47.1/101.7 MB 5.1 MB/s eta 0:00:11
   ------------------ --------------------- 47.2/101.7 MB 5.0 MB/s eta 0:00:11
   ------------------ --------------------- 47.5/101.7 MB 5.0 MB/s eta 0:00:11
   ------------------ --------------------- 47.6/101.7 MB 5.0 MB/s eta 0:00:11
   ------------------ --------------------- 47.9/101.7 MB 5.0 MB/s eta 0:00:11
   ------------------ --------------------- 48.1/101.7 MB 5.0 MB/s eta 0:00:11
   ------------------ --------------------- 48.3/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 48.5/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 48.7/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 49.0/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 49.1/101.7 MB 4.8 MB/s eta 0:00:11
   ------------------- -------------------- 49.4/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 49.6/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 49.9/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 50.1/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 50.3/101.7 MB 4.9 MB/s eta 0:00:11
   ------------------- -------------------- 50.5/101.7 MB 4.8 MB/s eta 0:00:11
   ------------------- -------------------- 50.7/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 51.0/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 51.1/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 51.4/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 51.6/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 51.9/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 52.0/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 52.3/101.7 MB 4.8 MB/s eta 0:00:11
   -------------------- ------------------- 52.5/101.7 MB 4.7 MB/s eta 0:00:11
   -------------------- ------------------- 52.6/101.7 MB 4.7 MB/s eta 0:00:11
   -------------------- ------------------- 52.9/101.7 MB 4.7 MB/s eta 0:00:11
   -------------------- ------------------- 53.1/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 53.4/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 53.6/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 53.8/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 54.0/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 54.3/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 54.5/101.7 MB 4.6 MB/s eta 0:00:11
   --------------------- ------------------ 54.7/101.7 MB 4.7 MB/s eta 0:00:11
   --------------------- ------------------ 54.9/101.7 MB 4.6 MB/s eta 0:00:11
   --------------------- ------------------ 55.1/101.7 MB 4.6 MB/s eta 0:00:11

In [21]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

# Calculate imbalance ratio for class 1
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()

scale_pos_weight = negative_count / positive_count

print("Negative:", negative_count)
print("Positive:", positive_count)
print("scale_pos_weight:", scale_pos_weight)

Negative: 13270
Positive: 154
scale_pos_weight: 86.16883116883118

In [22]:
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [23]:
y_pred_xgb = xgb_model.predict(X_test)

print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.99      0.70      0.82      3318
           1       0.02      0.47      0.03        38

    accuracy                           0.70      3356
   macro avg       0.50      0.59      0.43      3356
weighted avg       0.98      0.70      0.81      3356

In [24]:
y_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

for threshold in [0.1, 0.2, 0.3, 0.4, 0.5]:
    y_pred_xgb_threshold = (y_proba_xgb >= threshold).astype(int)

    print("Threshold:", threshold)
    print(classification_report(y_test, y_pred_xgb_threshold))
    print("-" * 50)

Threshold: 0.1
              precision    recall  f1-score   support

           0       0.99      0.09      0.16      3318
           1       0.01      0.95      0.02        38

    accuracy                           0.10      3356
   macro avg       0.50      0.52      0.09      3356
weighted avg       0.98      0.10      0.16      3356

--------------------------------------------------
Threshold: 0.2
              precision    recall  f1-score   support

           0       0.99      0.17      0.29      3318
           1       0.01      0.92      0.02        38

    accuracy                           0.18      3356
   macro avg       0.50      0.54      0.16      3356
weighted avg       0.98      0.18      0.28      3356

--------------------------------------------------
Threshold: 0.3
              precision    recall  f1-score   support

           0       1.00      0.27      0.43      3318
           1       0.01      0.92      0.03        38

    accuracy                           0.28      3356
   macro avg       0.51      0.60      0.23      3356
weighted avg       0.99      0.28      0.42      3356

--------------------------------------------------
Threshold: 0.4
              precision    recall  f1-score   support

           0       0.99      0.43      0.60      3318
           1       0.01      0.66      0.03        38

    accuracy                           0.43      3356
   macro avg       0.50      0.54      0.31      3356
weighted avg       0.98      0.43      0.59      3356

--------------------------------------------------
Threshold: 0.5
              precision    recall  f1-score   support

           0       0.99      0.70      0.82      3318
           1       0.02      0.47      0.03        38

    accuracy                           0.70      3356
   macro avg       0.50      0.59      0.43      3356
weighted avg       0.98      0.70      0.81      3356

--------------------------------------------------